INSERT INTO public.allowed_commands (command, description)
VALUES
    ('bash', 'GNU Bourne-Again SHell interpreter.'),
    ('cat', 'Display file content.'),
    ('echo', 'Display a line of text, often used for scripting.'),
    ('ls', 'List directory contents.'),
    ('mkdir', 'Create new directories.'),
    ('node', 'Node.js runtime, for executing scripts.'),
    ('nohup', 'No Hang Up: para ejecutar comandos en segundo plano, inmune a cuelgues o cierres de terminal.'),
    ('npm', 'Node Package Manager: para instalar y gestionar dependencias de Node.js.'),
    ('npx', 'Node Package Execute: para ejecutar paquetes de Node.js.'),
    ('pkill', 'Signal processes based on name (e.g., to stop a running server).'),
    ('pnpm', 'Performant NPM - Another alternative package manager.'),
    ('rm', 'Remove: para eliminar archivos o directorios (sujeto a validación de ruta segura).'),
    ('sh', 'Standard command language interpreter.'),
    ('touch', 'Create new empty files.'),
    ('yarn', 'Yarn Package Manager - An alternative to npm.'),
    ('apt-get', 'Permite la gestión de paquetes en sistemas Debian/Ubuntu.'),
    ('curl', 'Permite la descarga de archivos y la realización de solicitudes HTTP.'),
    ('sudo', 'Permite ejecutar comandos con privilegios de superusuario (sujeto a validación adicional).'),
    ('cd', 'Change Directory: para navegar entre directorios.'),
    ('pwd', 'Print Working Directory: para mostrar el directorio de trabajo actual.'),
    ('which', 'para localizar un comando.'),
    ('grep', 'Global Regular Expression Print: para buscar patrones en texto.'),
    ('sed', 'Stream Editor: para filtrar y transformar texto.'),
    ('awk', 'para procesar y analizar texto.'),
    ('tee', 'para leer de la entrada estándar y escribir en la salida estándar y en archivos.'),
    ('chmod', 'Change Mode: para cambiar permisos de archivos.'),
    ('install', 'para copiar archivos y establecer atributos.'),
    ('dirname', 'para extraer el nombre del directorio de una ruta.'),
    ('ss', 'Socket Statistics: para inspeccionar sockets (usado para verificar puertos).'),
    ('df', 'Disk Free: para mostrar el uso del espacio en disco.'),
    ('free', 'para mostrar el uso de memoria.'),
    ('top', 'para mostrar procesos en ejecución y uso de recursos.')
ON CONFLICT (command) DO UPDATE SET description = EXCLUDED.description;